version: '3.3'
services:
    mysql-service:
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=Test@12345
            - MYSQL_DATABASE=bookstore
            - MYSQL_USER=node_user
            - 'MYSQL_PASSWORD=NodePass@123#'
        container_name: mysql_db_svc
        image: 'mysql:8.0.34'
        volumes:
            - mysql_data:/var/lib/mysqld
        networks:
            - app_network
    node-app-service:
        ports:
            - '8000:3000'
        build: .
        container_name: node_app_container
        networks:
            - app_network
volumes:
    mysql_data:
networks:
    app_network:
    


