name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Set this in GitHub Secrets
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}  # Set this in GitHub Secrets

      # Step 4: Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # Use the root directory where the Dockerfile is located
          push: true  # Push the image to Docker Hub
          tags: sandip1991/test_nodejs:latest  # Replace with your Docker Hub repository and image name

      # Step 5: Install Docker Compose (optional, if needed)
      - name: Install Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')
          sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      # Step 6: Deploy application using Docker Compose
      - name: Deploy application
        run: |
          echo "Deploying the application with Docker Compose"
          docker-compose up -d
          
